### ISSUE TITLE
Uppercase keys support

### ISSUE THREAD

**Issue by Christophe668** [square/phrase#9] opened 2015-01-20 13:00 UTC
Hi,

I'm getting a crash when using  **Phrase.from("This is an {EXAMPLE}");**
Throwing a *'Unexpected character 'E'; expected key.'*

Could you add support for uppercase keys? It would help me since i'm not controlling the strings I receive.

Thank you !

**Comment by quinnjn** [comment] 2015-01-28 22:36
I'd like to expand this request further. Is there a reason why phrase doesn't allow uppercase characters, symbols, or numbers?

**Comment by dlew** [comment] 2015-02-18 19:53
It seems like it ought to accept any value that is valid as an Android resource.

I'm willing to do a PR on this but I'm curious if there is a reason it was purposefully avoided before I jump in.

**Comment by quinnjn** [comment] 2015-02-18 20:51
@dlew ditto. I have something in the works but I've been waiting for input on this issue. Their exists a test case stating [no uppercase characters](https://github.com/square/phrase/blob/master/src/test/java/com/squareup/phrase/PhraseTest.java#L140) so I'd like some feedback on why.

**Comment by Querschlag** [comment] 2015-07-05 09:54
If that's an expected behaviour I suggest to include this in the documentation. I struggled quiet a while to find the cause with the error 'java.lang.IllegalArgumentException: Missing closing brace: }' ...

**Comment by loganj** [comment] 2016-02-04 20:31
We don't support uppercase characters because we haven't seen a need.  If anything we could ignore case, but why?

Closing, feel free to reopen if you're still interested and care to make the case.

Sorry for the pun.

**Closed by loganj** 2016-02-04 20:31 UTC

**Comment by rocboronat** [comment] 2016-03-10 14:16
This issue is a key one. Is what Phrase newcomers expects Phrase to do. Please, reopen it and accept #17. Thanks!

**Comment by ryust** [comment] 2017-07-19 21:14
Just because you don't see a need doesn't mean there isn't one. I have a use case of migrating from a different substitution library that used uppercase for their keys and I can't have all my users manually translating their uppercase parameters to lowercase. I've made the case.

The bigger question is instead of "why", is "why not"?

**Comment by JakeWharton** [comment] 2017-07-19 21:16
Nope. For libraries the question is always "why".

**Comment by pforhan** [comment] 2017-07-19 21:24
I think there's a very good case for fixing the terrible error message.  When that's done I think this will matter less to folks as they'll get immediate feedback on the problem, and won't have to dig.

I'll see if I can put a pull request together, I just ran into this last week.

**Comment by pforhan** [comment] 2017-07-19 21:35
Oh, #33 almost does this, test is a little weak though.

**Comment by ryust** [comment] 2017-07-19 22:03
Ok, then I'll rephrase my question, "why lowercase"? Someone made a binary decision... could have been uppercase.

**Comment by JakeWharton** [comment] 2017-07-19 22:37
It's what Android uses for names. It's what JSON used for keys. It's an
obvious choice over uppercase.

**Comment by ryust** [comment] 2017-07-19 23:32
The Android standard for constants seems to be uppercase in most of the projects I've seen. Parameterized strings with uppercase keys would also be much easier to identify... so in another time and place the uppercase decision could have as easily been justified by someone else.

Not trying to give you a hard time, and actually I don't care as I've moved on to different software, but the polarized right/wrong views just irk me.

**Comment by JakeWharton** [comment] 2017-07-19 23:34
That's Java constants, not Android resources. No one said uppercase is
wrong, it's merely not something supported by design. A reduced feature set
focuses a library. One which says "yes" to everything isn't a library I
want to use, or one we want to build.

**Comment by dlew** [comment] 2017-07-20 00:25
> actually I don't care as I've moved on to different software

If it doesn't matter to you, then maybe you shouldn't be taking up other peoples' time and effort with the matter? Maintaining a library is a chore, there's no need to make it harder than it already is.

**Comment by rocboronat** [comment] 2017-07-20 07:20
At least, improve the error message `Unexpected character 'E'; expected key.`

What about `Unexpected character 'E'. Phrase keys must be lowercase.`

**Comment by pforhan** [comment] 2017-07-21 01:05
See #35 for a fix to the error messages for invalid key names.
